export interface TagOption {
  value: string;
  label: string;
  icon: string | null;
}

export const TagOptions: TagOption[] = [
  { value: 'design', label: 'design', icon: null },
  { value: 'typography', label: 'typography', icon: null },
  { value: 'css', label: 'css', icon: null },
  { value: 'typescript', label: 'typescript', icon: null },
  { value: 'javascript', label: 'javascript', icon: null },
  { value: 'AI', label: 'AI', icon: null },
  { value: 'machine learning', label: 'machine learning', icon: null },
  { value: 'inspiration', label: 'inspiration', icon: null },
  { value: 'packages', label: 'packages', icon: null },
  { value: 'colors', label: 'colors', icon: null },
  { value: 'blogs', label: 'blogs', icon: null },
  { value: 'github repository', label: 'github repository', icon: null },
  { value: 'video', label: 'video', icon: null },
  { value: 'portfolio', label: 'portfolio', icon: null },
  { value: 'podcast', label: 'podcast', icon: null },
  { value: 'blog', label: 'blog', icon: null },
  { value: 'react', label: 'react', icon: null },
  { value: 'angular', label: 'angular', icon: null },
  { value: 'vue', label: 'vue', icon: null },
  { value: 'D3', label: 'D3', icon: null },
  { value: 'Flask', label: 'Flask', icon: null },
  { value: 'Node', label: 'Node', icon: null },
  { value: 'Python', label: 'Python', icon: null },
  { value: 'HTML', label: 'HTML', icon: null },
  { value: 'Frontend', label: 'Frontend', icon: null },
  { value: 'Backend', label: 'Backend', icon: null },
  { value: 'tutorial', label: 'tutorial', icon: null },
  { value: 'Generative Art', label: 'Generative Art', icon: null },
  { value: 'Mobile', label: 'Mobile', icon: null },
  { value: 'Illustration', label: 'Illustration', icon: null },
  { value: 'Transitions', label: 'Transitions', icon: null },
  { value: 'Animations', label: 'Animations', icon: null },
  { value: 'Three.js', label: 'Three.js', icon: null },
  { value: 'Svelte', label: 'Svelte', icon: null },
  { value: 'SPA', label: 'SPA', icon: null },
  { value: 'Interview Prep', label: 'Interview Prep', icon: null },
  { value: 'UX', label: 'UX', icon: null },
  { value: 'UI', label: 'UI', icon: null },
  { value: 'UX Writing', label: 'UX Writing', icon: null },
  { value: 'Microinteractions', label: 'Microinteractions', icon: null },
  { value: 'Computer Science', label: 'Computer Science', icon: null },
  { value: 'Games', label: 'Games', icon: null },
  { value: 'Brutalist', label: 'Brutalist', icon: null },
  { value: 'JS Animations', label: 'JS Animations', icon: null },
  { value: 'Web GL', label: 'Web GL', icon: null },
  { value: 'Storytelling', label: 'Storytelling', icon: null },
  { value: 'Talks/Interviews', label: 'Talks/Interviews', icon: null },
  { value: 'Article', label: 'Article', icon: null },
  { value: 'Tool', label: 'Tool', icon: null },
  { value: 'Maps', label: 'Maps', icon: null },
  { value: 'Resource', label: 'Resource', icon: null },
  { value: 'Golang', label: 'Golang', icon: null },
];
