export interface TagOption {
  value: string;
  label: string;
  icon: string | null;
}

export const TagOptions: TagOption[] = [
  { value: 'design', label: 'design', icon: null },
  { value: 'typography', label: 'typography', icon: null },
  { value: 'rust', label: 'rust', icon: null },
  { value: 'WASM', label: 'WASM', icon: null },
  { value: 'frontend', label: 'frontend', icon: null },
  { value: 'the web!', label: 'the web!', icon: null },
  { value: 'images', label: 'images', icon: null },
  { value: 'css', label: 'css', icon: null },
  { value: 'typescript', label: 'typescript', icon: null },
  { value: 'javascript', label: 'javascript', icon: null },
  { value: 'AI', label: 'AI', icon: null },
  { value: 'machine learning', label: 'machine learning', icon: null },
  { value: 'inspiration', label: 'inspiration', icon: null },
  { value: 'packages', label: 'packages', icon: null },
  { value: 'colors', label: 'colors', icon: null },
  { value: 'blogs', label: 'blogs', icon: null },
  { value: 'web3', label: 'web3', icon: null },
  { value: 'crypto', label: 'crypto', icon: null },
  { value: 'github repository', label: 'github repository', icon: null },
  { value: 'video', label: 'video', icon: null },
  { value: 'data visualization', label: 'data visualization', icon: null },
  { value: 'portfolio', label: 'portfolio', icon: null },
  { value: 'podcast', label: 'podcast', icon: null },
  { value: 'blog', label: 'blog', icon: null },
  { value: 'react', label: 'react', icon: null },
  { value: 'angular', label: 'angular', icon: null },
  { value: 'vue', label: 'vue', icon: null },
  { value: 'D3', label: 'D3', icon: null },
  { value: 'flask', label: 'flask', icon: null },
  { value: 'node', label: 'node', icon: null },
  { value: 'python', label: 'python', icon: null },
  { value: 'HTML', label: 'HTML', icon: null },
  { value: 'backend', label: 'backend', icon: null },
  { value: 'tutorial', label: 'tutorial', icon: null },
  { value: 'generative art', label: 'generative art', icon: null },
  { value: 'mobile', label: 'mobile', icon: null },
  { value: 'illustration', label: 'illustration', icon: null },
  { value: 'transitions', label: 'transitions', icon: null },
  { value: 'animations', label: 'animations', icon: null },
  { value: 'three.js', label: 'three.js', icon: null },
  { value: 'svelte', label: 'svelte', icon: null },
  { value: 'spa', label: 'spa', icon: null },
  { value: 'interview prep', label: 'interview prep', icon: null },
  { value: 'ux', label: 'ux', icon: null },
  { value: 'ui', label: 'ui', icon: null },
  { value: 'ux writing', label: 'ux writing', icon: null },
  { value: 'microinteractions', label: 'microinteractions', icon: null },
  { value: 'computer science', label: 'computer science', icon: null },
  { value: 'games', label: 'games', icon: null },
  { value: 'brutalist', label: 'brutalist', icon: null },
  { value: 'js animations', label: 'js animations', icon: null },
  { value: 'web gl', label: 'web gl', icon: null },
  { value: 'storytelling', label: 'storytelling', icon: null },
  { value: 'talks/interviews', label: 'talks/interviews', icon: null },
  { value: 'article', label: 'article', icon: null },
  { value: 'tools', label: 'tools', icon: null },
  { value: 'maps', label: 'maps', icon: null },
  { value: 'resource', label: 'resource', icon: null },
  { value: 'golang', label: 'golang', icon: null },
  { value: 'accessibility', label: 'accessibility', icon: null },
];
